name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ '**' ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal
    steps:
    - uses: actions/checkout@v2
    - name: Install v4l2loopback
      run: |
        apt-get update && \
        apt-get install -y --no-install-recommends --no-install-suggests v4l2loopback-dkms v4l2loopback-utils
    - name: Install dependencies
      run: shards install
    - name: Run tests
      run: crystal spec
